version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3005:3001"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend
